export const PrivacyPolicyPage = () => {
  return (
      <div className="container">
        <h1 className="mt-4">Privacy Policy</h1>
  
        <div className="mt-4">
          <h2>Introduction</h2>
          <p>
            Our priority is to guarantee the security of your Personal Data and protect your privacy throughout your journey with Sexto Andar, from the moment you register on our platform to the support we provide you as our customer.
          </p>
          <p>
            The processing of your personal data is essential for us to offer our services, and by continuing to use our platform, you are aware of and agree to the processing of your personal data in accordance with the terms of this Privacy Policy ("Policy").
          </p>
        </div>
  
        <div className="mt-4">
          <h2>What data do we collect?</h2>
          <p>
            The General Data Protection Law ("LGPD") defines personal data as information that identifies or makes a person identifiable. To provide our services and offer our products, we collect the following types of data:
          </p>
          <ul>
            <li>Identification data: Your full name, email, phone number, address, ZIP code, CPF (Brazilian Taxpayer Registry), RG (Identification Card), date of birth, and password.</li>
            <li>Navigation data: Information generated by the use of our platforms, such as IP address, browsing provider, network connection, cookies, geolocation data (when authorized on your device), device operating system, network, and device performance, accessed services, interactions performed, and device ID.</li>
            <li>Third-party data: Information obtained through public sources, service providers, or partners, always in compliance with Brazilian legislation. For example: credit history, scores generated by credit agencies, financial restrictions, data necessary to enable financial transactions, complementary information, and responses to your demands. You can review the Privacy Policies of the third parties with whom you interact on their own websites.</li>
          </ul>
        </div>
  
        <div className="mt-4">
          <h2>How do we use your data?</h2>
          <p>
            We use the personal data you provide when creating an account on Sexto Andar for the following purposes:
          </p>
          <ul>
            <li>Identify and authenticate you properly on our platforms.</li>
            <li>Keep your registration up to date and contact you by phone, email, WhatsApp, or other means of communication.</li>
            <li>Comply with the terms of this Policy and the Terms of Use of our products and services.</li>
            <li>Know you better and continue innovating, improving, and developing our products.</li>
            <li>Inform about changes in our terms, services, or policies (including this Policy).</li>
            <li>Identify and authenticate you properly on our platforms.</li>
          </ul>
        </div>
      </div>
  );
};

